config/routes.rb
Decydr::Application.routes.draw do

  resources :events do
    get 'today', :on => :collection    
  end

  root :to => 'home#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :begin_time, :display_name, :end_time, :name, :web_link, :description
  scope :today, lambda { where("begin_time BETWEEN '#{DateTime.now.beginning_of_day}' AND '#{DateTime.now.end_of_day}' OR
                                end_time BETWEEN '#{DateTime.now.beginning_of_day}' AND '#{DateTime.now.end_of_day}'") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  def today
    @events = Event.today
    render :index
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @events = Event.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/events/_event.html.erb
<table>
  <tr>
    <%= event.display_name %>
  </tr>
</table>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :begin_time %><br />
    <%= f.datetime_select :begin_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br />
    <%= f.datetime_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :display_name %><br />
    <%= f.text_field :display_name %>
  </div>
  <div class="field">
    <%= f.label :web_link %><br />
    <%= f.text_field :web_link %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Today</h1>

<table class="todays-events">

<% @events.each do |event| %>
  <tr>
    <td><%= event.name %></td>
    <td><%= event.begin_time.strftime("%-I:%M %p") %> - <%= event.end_time.strftime("%-I:%M %p") %></td>
    <% if params["admin"] == 'true' %>
      <td><%= link_to 'Show', event %></td>
      <td><%= link_to 'Edit', edit_event_path(event) %></td>
      <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
    <td>Liked</td>
  </tr>
  <tr class="details">
    <td><img src="http://lorempixel.com/<%= rand(400)%>/<%= rand(200)%>/"></td>
    <td><%= event.description %></td>
    <td>
      <%= image_tag 'mike.png', width: '30px' %>
      <%= image_tag 'joe-dirt.jpg', width: '30px' %>
    </td>
  </tr>
<% end %>
</table>

<br />

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @event.name %>
</p>

<p>
  <b>Begin time:</b>
  <%= @event.begin_time %>
</p>

<p>
  <b>End time:</b>
  <%= @event.end_time %>
</p>

<p>
  <b>Display name:</b>
  <%= @event.display_name %>
</p>

<p>
  <b>Web link:</b>
  <%= @event.web_link %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/home/index.html.erb
<div id="home">
    <div class="story">
        <div class="container-fluid">
            <div class="row-fluid">
                <div class="span3">
                </div>
                <div class="span9">
                    <div class="row-fluid">
                        <div class="span5">
                          <header>
                            <hgroup>
                              <h1>Decydr <span class="rnd">{0.1}</span></h1>
                              <h2>Your one-stop shop for events and conditions</h2>
                              <p>Conditions? Check.</p><p> Weather? Check.</p><p> Friends? Check.</p><p> Decydr is a website and mobile app that aggregates local event information into one place, and shows you which ones your friends are most interested in.</p>
                            </hgroup>
                            <p><a class="btn" href="#events">See Events Now »</a></p>
                          </header>
                        </div>
                        <!--/span-->
                  </div>
                    <!--/row-->
                </div>
                <!--/span-->
            </div>
            <!--/row-->
        </div>
    </div>
    <!--.story-->
</div>
<!--#intro-->

<!--#events-->
<div id="events">
  <div class="container-fluid">
    <div class="story">
        <div class="row-fluid">
                <h1>Events and Conditions <span class="rnd">fresh</span></h1>
                <p>Stepping outside in Central Oregon? This is your resource to the latest events,
                  trail conditions, slope style and weather.</p>
                 <div class="span10">
<section>
  <h2>Today:</h2>
  <%= javascript_tag do %>
    $(document).ready(function() {

        // page is now ready, initialize the calendar...

        $('#calendar').fullCalendar({
          defaultView: 'agendaDay',
          height: 300,
          columnFormat: {
              month: '',    // Mon
              week: '', // Mon 9/7
              day: ''  // Monday 9/7
                      },
          events: [
                  <% @events.each_with_index do |event, index| %>
                  {
                    title: "<%= event.display_name %>",
                    start: new Date(<%= event.begin_time.year %>,<%= event.begin_time.month - 1 %>,<%= event.begin_time.day %>,<%= event.begin_time.hour %>,<%= event.begin_time.strftime('%M') %>),
                    end: new Date(<%= event.end_time.year %>,<%= event.end_time.month - 1%>,<%= event.end_time.day %>,<%= event.end_time.hour %>,<%= event.end_time.strftime('%M') %>),
                    allDay: false
                  }<%= ',' if index < (@events.length - 1) %>
                  <% end %>
                 ]
        })

    });
  <% end %>
  <div id="calendar"></div>
</section>
<section id="splash-tables">

      <ul class="thumbnails">
        <li class="span3">
          <h2>Events</h2>
          <table>
            <tr><td><%= link_to('Today', today_events_path) %></td></tr>
            <tr><td><%= link_to('This Weekend','') %></td></tr>
            <tr><td><%= link_to('and Beyond','') %></td></tr>
          </table>
        </li>
        <li class="span3">
          <h2>Conditions</h2>
          <table>
            <tr><td><%= link_to('Today','') %></td></tr>
            <tr><td><%= link_to('This Weekend','') %></td></tr>
            <tr><td><%= link_to('and Beyond','') %></td></tr>
          </table>
        </li>
        <li class="span3">
          <h2>Providers</h2>
          <table>
            <tr><td><%= link_to('Today','') %></td></tr>
            <tr><td><%= link_to('This Weekend','') %></td></tr>
            <tr><td><%= link_to('and Beyond','') %></td></tr>
          </table>
        </li>
        <li class="span3">
          <h2>Gear</h2>
          <table>
            <tr><td><%= link_to('Today','') %></td></tr>
            <tr><td><%= link_to('This Weekend','') %></td></tr>
            <tr><td><%= link_to('and Beyond','') %></td></tr>
          </table>
        </li>
      </ul>

      <% if false %>
      <h2>Twitter</h2>
<section id="twitter">
  <%= javascript_tag do %>
    $('#twitter').socialist({
        networks: [
            {name:'twitter',id:'mtbachelor'},
            {name:'twitter',id:'twisitbend'}
        ],
        isotope:false,
        random:false,
        maxResults: 5,
        fields:['source','heading','text','date']
    });
  <% end %>
</section>
      <ul class="thumbnails">
        <li class="span3">
          <a href="#" class="thumbnail">
            <img src="http://placehold.it/260x180" alt="">
          </a>
        </li>
        <li class="span3">
          <a href="#" class="thumbnail">
            <img src="http://placehold.it/260x180" alt="">
          </a>
        </li>
        <li class="span3">
          <a href="#" class="thumbnail">
            <img src="http://placehold.it/260x180" alt="">
          </a>
        </li>
      </ul>
<% end %>
    </div>


    </div>
    </div><!--.story-->
    </div>
</div>
<!--#events-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Decydr</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,800' rel='stylesheet' type='text/css'> <style> #page {opacity:0;}</style>
</head>

<body data-spy="scroll" data-offset="10" id="page" class="<%= controller.action_name %>">

<header>
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container-fluid"> <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </a>
                <div class="nav-collapse">
                    <ul id="navi" class="nav">
                        <li><a href="/#home">Home</a></li>
                        <li><a href="/#events">Events and Conditions</a></li>
                    </ul>
                </div>
          </div>
        </div>
    </div>
</header>

<%= yield %>

<!-- Le JS -->
<script>
$(document).ready(function(){
  $('#navi').localScroll(800);
  RepositionNav();
  $(window).resize(function(){
    RepositionNav();
  });
  // .parallax(xPosition, adjuster, inertia, outerHeight) options:
  // xPosition - Horizontal position of the element.
  // adjuster - y position to start from.
  // inertia - speed to move relative to vertical scroll. Example: 0.1 is one tenth the speed of scrolling, 2 is twice the speed of scrolling.
  // outerHeight (true/false) - Whether or not jQuery should use it's outerHeight option to determine when a section is in the viewport.
  $('#intro').parallax("50%", 0, 0.1, true);
  $('#second').parallax("50%", 0, 0.1, true);
  $('.bg').parallax("5%", 3000, 0.8, true);
  $('.bg2').parallax("30%", 3500, 0.8, true);
  $('#events').parallax("50%", 0, 0.1, true);
  $('#fourth').parallax("50%", 0, 0.1, true);
})
  $('#navbar').scrollspy();
</script>

<script>
$(".collapse").collapse()
</script>


<!-- page fade effect - this simple trick first waits for page to load(images, content) and after it's loaded fades it. You can remove it by deleting this section. -->
<!-- read documentation -->
<script>
$(document).ready(function() {
  $('#page').fadeTo(1500, 1);
});
</script>
<!-- /page fade effect -->

</body>
</html>